### ISSUE TITLE
Add initialValue to reduce method

### ISSUE THREAD

**Issue by RinatValiullov** [nas5w/javascript-tips-and-tidbits#15]
I think It will be better add *initialValue* in the section: [Array Methods](https://github.com/nas5w/javascript-tips-and-tidbits#array-methods)  in `reduce()` method. In my opinion, it is better to clarify the internal logic of this method, isn't it?

**Comment by nas5w** [comment]
Definitely! Any thoughts on how the example should be clarified? Perhaps just a "Note" stating that an optional second parameter can be provided establishing an initial value?

**Comment by RinatValiullov** [comment]
I think @nas5w make more example codes with `reduce()` where user can see intent of optional _initialValue_

```js
let arr = [1, 2, 3, 4, 5];

// removed initial value from reduce (no 0)
// If there’s no initial, then reduce takes the first element of the array as the initial value and starts the iteration from the 2nd element
console.log( result ); // 15
let result = arr.reduce((sum, current) => sum + current);
```

but 
```js
let arr = [];

// Error: Reduce of empty array with no initial value
// if the initial value existed, reduce would return it for the empty arr.
arr.reduce((sum, current) => sum + current);

// Uncaught TypeError: Reduce of empty array with no initial value
```
**So it’s advised to always specify the initial value.**

**Comment by nas5w** [comment]
Okay, what are your thoughts on this being the updated text:

**reduce:** accumulate values as specified in function

```javascript
const arr = [1, 2, 3, 4, 5, 6];
const reduced = arr.reduce((total, current) => total + current, 0);
console.log(reduced);
// 21
```

*Note:* It is always advised to specify an *initialValue* or you could receive an error. For example:

```javascript
const arr = [];
const reduced = arr.reduce((total, current) => total + current);
console.log(reduced);
// Uncaught TypeError: Reduce of empty array with no initial value
```

**Comment by RinatValiullov** [comment]
> Okay, what are your thoughts on this being the updated text:
> 
> **reduce:** accumulate values as specified in function
> 
> ```js
> const arr = [1, 2, 3, 4, 5, 6];
> const reduced = arr.reduce((total, current) => total + current, 0);
> console.log(reduced);
> // 21
> ```
> 
> _Note:_ It is always advised to specify an _initialValue_ or you could receive an error. For example:
> 
> ```js
> const arr = [];
> const reduced = arr.reduce((total, current) => total + current);
> console.log(reduced);
> // Uncaught TypeError: Reduce of empty array with no initial value
> ```

Good and clear example.
I think it will be great to add a comment also: _If there’s no initialValue, then reduce takes the first element of the array as the initialValue and starts the iteration from the 2nd element_

**Comment by nas5w** [comment]
Are you interested in doing the pull request to close this issue?

**Comment by RinatValiullov** [comment]
> Are you interested in doing the pull request to close this issue?

Yeah, sure. I will do it, OK?

**Comment by nas5w** [comment]
Yes please!
