### ISSUE TITLE
Number of primitive types

### ISSUE THREAD

**Issue by j127** [nas5w/javascript-tips-and-tidbits#24]
I think that JavaScript now has [seven primitive types](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures): Boolean, Null, Undefined, String, Number, Symbol, and BigInt.

**Comment by nas5w** [comment]
Thanks, do you want to make a PR to fix this? Otherwise I can just make the change.

**Comment by j127** [comment]
Sure, I've just made a pull request.

I made a proposal to remove the backticks there, because I think that `Boolean` is a constructor function while "Boolean" is a type that can have two values: `true` or `false`. If you prefer it the other way I could revert that before merging.

They also write it like this in the [ECMAScript 2020 standard](https://tc39.es/ecma262/):

> A primitive value is a member of one of the following built-in types: Undefined, Null, Boolean, Number, BigInt, String, and Symbol; an object is a member of the built-in type Object; and a function is a callable object.
