### ISSUE TITLE
Great article, tiny correction.

### ISSUE THREAD

**Issue by JackLingwood** [nas5w/javascript-tips-and-tidbits#4]
Great article !

Tiny correction.

It says:
Accordingly, reassigning var2 has not effect on var1.

It should say:
Accordingly, reassigning var2 has no effect on var1.

**Comment by nas5w** [comment]
Thanks for the catch @JackLingwood! Feel free to create a pull request with the correction if you'd like the contribution, otherwise I can make the fix this evening.
